### ISSUE TITLE
Updating the list

### ISSUE THREAD

**Issue by rkakash59** [Lee-JaeWon/2024-Arxiv-Paper-List-Gaussian-Splatting#2]
@Lee-JaeWon I have been following this list for long to keep track of Gaussian splatting research. 
It is by far the best and most exhaustive list. Thank you so much for your great work.

Please do keep updating it :) .

**Comment by Lee-JaeWon** [comment]
@rkakash59 
Sorry for the late update. I've been rather busy.

I'm trying to figure out how to make it update automatically using github actions or something.

If you want to contribute, feel free to do so!
